//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebTemplate.Models.AspNetUsers
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.AspNetCore.Identity;

    public partial class AspNetUserClaim : IdentityUserClaim<string>
    {

        //[Key]
        //public int Id { get; set; }
        //public string UserId { get; set; }
        //public string ClaimType { get; set; }
        //public string ClaimValue { get; set; }

        //public virtual AspNetUser AspNetUser { get; set; }
    }
}
