//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebTemplate.Models.AspNetUsers
{
    using Microsoft.AspNetCore.Identity;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AspNetRole : IdentityRole<string>
    {
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRole() : base()
        {//
          //  this.AspNetUsers = new HashSet<AspNetUser>();
        }

        public AspNetRole(string roleName) : base(roleName)
        {
           // this.AspNetUsers = new HashSet<AspNetUser>();
        }

        //[Key]
        //public string Id { get; set; }
        //public string Name { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
