//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebTemplate.Models.Entity.Blog
{
    using System;
    using Microsoft.EntityFrameworkCore;

    public class BlogEntities : DbContext
    {
        public BlogEntities( DbContextOptions<BlogEntities> options ) : base( options ) { }

        public virtual DbSet<BlogComment> BlogComment { get; set; }

        public virtual DbSet<BlogPost> BlogPosts { get; set; }
    }
}
