//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebTemplate.Models.Entity.Blog
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class BlogPost
    {

        [Key]
        public int BlogPostID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime PublishedOn { get; set; }

        public virtual ICollection<BlogComment> BlogComments { get; set; }
    }
}
