//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreWebTemplate.Models.Entity.Blog
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class BlogComment
    {
        [Key]
        public int CommentID { get; set; }
        [ForeignKey( "BlogPostID" )]
        public int BlogPostID { get; set; }
        public string Comment { get; set; }
        public DateTime CommentedOn { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
}
